### ISSUE TITLE
Incorrect example in README.md

### ISSUE THREAD

**Issue by jrieks** [akryl-kt/akryl-dom#1]
The below example does not compile, the error is caused by "hover", the message is:
```
Type mismatch.
Required: CssElement
Found: PseudoSelector
```
Example Code:
```
// Kotlin
val foo by css(
    color.red()
)

val bar by css(
    display.flex(),
    
    hover(
        background.gray()
    ),
    
    foo(
        flex(1, 1, 100.pct)
    )
)
```

**Comment by ashlanderr** [comment]
You need to add this import statement:

```kotlin
import io.akryl.dom.css.invoke
```

I'm using auto-import in IDEA, so I didn't realize it can be a problem.

This line doesn't work either:

```
background.gray()
```

You need to use `backgroundColor`. 

I will fix these issues in the README.
