### ISSUE TITLE
Make tag names and parameters comply with kotlinx-html notation

### ISSUE THREAD

**Issue by altavir** [akryl-kt/akryl-dom#2]
I understand, that it is different library, but there is already an ecosystem around kotlinx-html and react-kotlin, which uses the same naming.
The main thing is starting tags with small letters.

**Comment by ashlanderr** [comment]
I will change the tags' names. It's not a problem. 

Could you give me an example of attribute differences? I can't follow exactly the same naming in events, for example. I want events to be like `onClick`, but not like `onClickFunction`.

**Comment by altavir** [comment]
I do not think that `onClick` is critical. In basic kotlinx-html it is `onClick` anyway. The main thing are capital letters. I think that the rest follows specification and should not differ much.
